include:
  - docker-compose.kafka.yml
  - docker-compose.monitoring.yml
  - docker-compose.services.yml
  - docker-compose.elastic.yml

volumes:
  redis-data:
  es-data:

networks:
  fitrang-net:
    driver: bridge
