services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    networks:
      - fitrang-net
    volumes:
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf:ro

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093

      KAFKA_LISTENERS: >
        SASL_PLAINTEXT://broker:29092,
        SASL_PLAINTEXT_HOST://0.0.0.0:9092,
        CONTROLLER://broker:29093

      KAFKA_ADVERTISED_LISTENERS: >
        SASL_PLAINTEXT://broker:29092,
        SASL_PLAINTEXT_HOST://broker:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        SASL_PLAINTEXT:SASL_PLAINTEXT,
        SASL_PLAINTEXT_HOST:SASL_PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

networks:
  fitrang-net:
